### ISSUE TITLE
RpcWalletSpecification Missing?/Can't be imported

### ISSUE THREAD

**Issue by kimjust6** [koczadly/jNano#11]
RpcWalletSpecification can't be imported in the latest version.  Reverting back to 2.19.1 works.

Haven't really looked into too much detail as to why this is happening, I just know that 2.20 broke RpcWalletSpecification for me.

**Comment by koczadly** [comment]
Yeah hey, I'm really sorry but I replaced a few of the classes and methods used. I didn't think people were actually using the classes as I had only just introduced them a few weeks back.

If you check the RPC queries wiki it has the updated version, all functionality is still there. I'm on my phone at the minute so I can't easily send the link. StateBlockBuilder setter methods have also been changed if you were using those.

Apologies, I'll be sure to leave a proper notice or deprecate features first before making any breaking changes next time.

**Comment by kimjust6** [comment]
No worries.
I honestly didn't really look into it that deeply, and am sure I could have figured it out after some light reading.
I'm only using it for experimenting/fun, but the LocalRpcWalletAccount class really makes it easy to create wallets/send transactions.

Thanks for the work.

**Comment by koczadly** [comment]
Awesome, I'm glad you're finding the library helpful and of use 😊
If you have any other questions or feature requests just lemme know, I'd be happy to help

**Comment by koczadly** [comment]
Hey @kimjust6, if you're still using this library/feature in a project I'd advise you update to version `2.20.1`, there were a few bugs in the `LocalRpcWalletAccount` class. Shouldn't break anything, don't worry :)

**Comment by kimjust6** [comment]
thanks for the update.

I'll definitely use the latest version.

**Comment by kimjust6** [comment]
@koczadly This isn't really an issue with the library, (as it works fine locally) but when I push the project to heroku, for some reason I get an exception (Failed to retrieve pending blocks) and it has something to do with malformed JSON.

If you have time, I would appreciate any feedback or even just guidance on how to debug this.  (I am unsure of how to check the json that is being returned)


[btp-400-assignment1-logs-1618586981232.txt](https://github.com/koczadly/jNano/files/6326243/btp-400-assignment1-logs-1618586981232.txt)

**Comment by koczadly** [comment]
@kimjust6 I have a feeling it's to do with the RPC API you're using - in your public project you're using the Kalium internal API, which may not be exactly the same as the RPC protocol. I assume they're returning some custom error data, or the command it requires (`pending`) isn't supported by their API.

**Comment by koczadly** [comment]
@kimjust6 For debugging purposes (it's a bit messy because of the nested exceptions) you can try to catch the `WalletActionException`, then call `getCause()` to retrieve the `RpcInvalidResponseException` object. This should have a `getResponseBody()` method which you can print to the console, which returns the raw response string (which should always be a JSON value).

**Comment by kimjust6** [comment]
okay thanks. I'll give that a try.

**Comment by koczadly** [comment]
@kimjust6 It'll be a proxy API at the very least (checking and forwarding the requests to the node), sometimes these can throw unexpected non-JSON errors. If you print out the response string to the console and post it here I'll take a look, I haven't been able to reproduce this for myself.

**Comment by koczadly** [comment]
@kimjust6 Heya, did you manage to figure out what was causing the problem?

**Comment by kimjust6** [comment]
@koczadly I managed to get it fixed (but not entirely certain why)

I tried using my own node, and it seemed to fix itself.  A little bit confused as to why, (because the kalium node works locally, just not on heroku).  I imagine it had to do with what you mentioned regarding the kalium node not being a complete node and just an api?

My own node seems to be working on both heroku and locally.  
Thanks for following up. I appreciate your help.

**Comment by koczadly** [comment]
@kimjust6 No worries mate, if you got any other questions just give me a shout! If it all worked well locally, it sounds like your requests may have been getting blocked or rejected — perhaps your IP is somehow blacklisted or was polling too frequently? That's all I can really think of that would cause an inconsistency like that.

As I mentioned in the github issue on your repo, it might be best to cache your `LocalRpcWalletAccount` instances in a map and re-use them to reduce the number of RPC queries needed, but that's totally optional if everything's working.

**Comment by kimjust6** [comment]
Thanks. I will definitely look into it. 
I was just doing some testing yesterday and there seems to be some bugs in general that I will need to iron out.
And like you suggested, it's probably best if we import the seed from a config file of some sort.  (instead of just having it exposed in the repo)

**Comment by koczadly** [comment]
@kimjust6 If you're new to Spring (I am too), you can look into creating a bean class annotated with `@ConfigurationProperties` and simply using a `spring application.properties` file in the application directory (not sure how that works with Heroku).

As for the mapping of accounts, you could use something like this, then just call `getWalletAccount(int)` wherever you currently create an instance of it. This is also important for synchronization, as Spring web/mvc is multithreaded, which can cause conflicting fork blocks to be created in a Nano account chain.
```java
private final Map<Integer, LocalRpcWalletAccount> accounts = new ConcurrentHashMap<>();

public LocalRpcWalletAccount getWalletAccount(int accountNo) {
    return accounts.computeIfAbsent(accountNo, k -> new LocalRpcWalletAccount(
			WalletUtil.deriveKeyFromSeed(seed, k), rpcClient, blockProducer));
}
```

From what I recall, your send method still used the NANO/BAN ratio multiplication, this should also be updated to use the defined `UNIT_BAN` constant when calling `NanoAmount.valueOf()`.

**Comment by kimjust6** [comment]
I will definitely have to look into spring boot more to get a better feel for what different implementation options I have.

The hashmap that you suggested before was something I was discussing with my group members.  It seems to be the easiest route to go.

Your memory would serves you correctly regarding the nano/ban ratio situtation.  I changed it in some parts of the code, but I missed a few spots.  

I'll have time to tackle these issues sometime next week.  I'll keep you posted.

**Comment by koczadly** [comment]
@kimjust6 Awesome, good luck with the project! So awesome to finally see people make use of this library haha, I don't think it's been used for many projects.
