### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by JgBr123** [koczadly/jNano#15]
Every time i try to make a request to the rpc, the program crashes with this error. Example:

`
RpcQueryNode rpc = RpcServiceProviders.nanex();
RequestAccountBalance req = new RequestAccountBalance("nano_34qjpc8t1u6wnb584pc4iwsukwa8jhrobpx4oea5gbaitnqafm6qsgoacpiz");
ResponseBalance response = rpc.processRequest(req);
`

**Comment by JgBr123** [comment]
Oh nevermind, you are right, it was a dependecy issue, sorry for bothering.

**Comment by koczadly** [comment]
No worries at all mate. If you got any other questions I'm always here :)
