### ISSUE TITLE
Keepalive and Reconnect has been include?

### ISSUE THREAD

**Issue by bobbychen** [koczadly/jNano#18]
As just said, I wanna know did you processed keepalive and Reconnect ?

**Comment by koczadly** [comment]
Heya mate, you talking about the RPC client, callback server or something else? Callback server is deprecated and not recommended (and likely doesn't implement keepalive, though I cannot remember), RPC uses the built in `HttpURLConnection` which I believe is configured to reuse the connection when possible.

**Comment by bobbychen** [comment]
OK, I see. thanks for reply.
