### ISSUE TITLE
Examples for constructing Send blocks?

### ISSUE THREAD

**Issue by tjl-dev** [koczadly/jNano#19]
Hi, nice work here encapsulating the API, couple thoughts -

Just looking through the docs and tests but couldn't find an easy example for how to properly construct a Send or Receive block and publish it.  We can look up Nano docs and use that as a guide, but it would be nice to have a simple api or some quick examples, as from what I recall the block requirements/structure can be tricky and can change over time.

It would also be nice to have the low level block construction abstracted away so the api user would only need to provide a few basic details - construct a wallet from address/seed, then Send() from the wallet to a target address a given amount.

Lastly is nanex.cc (the one in example) rpc node still usable?

**Comment by koczadly** [comment]
Hiya mate, glad you like the API.

If you want to access an abstracted API for creating and publishing blocks for a particular account, [`LocalRpcWalletAccount`](https://www.javadoc.io/doc/uk.oczadly.karl/jnano/latest/uk/oczadly/karl/jnano/rpc/util/wallet/LocalRpcWalletAccount.html) may be what you're looking for. There's a small mention of it on the wiki pages somewhere, but the Javadoc should suffice. Basically, you provide a private key, RPC client, and a `BlockProducer`, and you can access send/receive/changeRep/getBalance functions for that particular account.

If you want to just create the blocks without publishing them, [`LocalWalletAccount`](https://www.javadoc.io/doc/uk.oczadly.karl/jnano/latest/uk/oczadly/karl/jnano/util/blockproducer/LocalWalletAccount.html) may be worth checking out, though I didn't _originally_ intend for it to be used on its own (but there's no reason you can't).

As for Nanex, I'm not sure - it seems to be 404'ing at the minute so I assume not, but I'll leave it in there for the time being.

Let me know if you have any other questions or run into problems, I'd be happy to help 😊

**Comment by tjl-dev** [comment]
Thanks! missed that class, and I see the javadoc has an example. 
Ended up constructing the block with reference to API docs again (setting link, querying for frontier etc).
