### ISSUE TITLE
IlligalArgumentException on creating new account.

### ISSUE THREAD

**Issue by letskingit** [koczadly/jNano#2]
`java.lang.IllegalArgumentException: class uk.oczadly.karl.jnano.rpc.request.wallet.RequestAccountCreate declares multiple JSON fields named work
`
Thats what I am getting while attempting your example.

**Comment by koczadly** [comment]
Ah sorry about that mate, seems like I forgot to change the field name when copy-pasting. If you're using the maven repo, I'll aim to get the version updated by the end of the day, but you can copy the contents of the `uk.oczadly.karl.jnano.rpc.request.wallet.RequestAccountCreate` into your own class (package/class name doesnt matter) if you need to immediately use the command.

Thanks for bringing this to my attention, I really appreciate it. I should probably get around to adding proper unit tests for these classes while I'm at it.

**Comment by letskingit** [comment]
Hey!
Yeah I'm using the maven repo. Don't be sorry, awesome contribution to the community, just a tiny issue. Let me know when the new version is out. 
Have built a Java library myself for xmr(on github), also mostly self taught.

**Comment by koczadly** [comment]
Cheers bro, I appreciate it. Just published the new version `2.0.1-V20` on maven central, should be available shortly.
