### ISSUE TITLE
Comptability with pippin

### ISSUE THREAD

**Issue by letskingit** [koczadly/jNano#6]
Hello!

I'm getting a 500 server error with pippin on creating an account.

Was wondering if you could make jnano more compatible with pippin.
Java log:
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:11338
Pippin log:
raise ValueError ('badly formed hexadecimal UUID string')

Error is raised on RequestAccountCreate

Notes about pippin:
APIs that are different between Pippin and the Nano node wallet.
account_list accepts a count parameter that defaults to 1000
Pippin has an auto_receive_on_send option that will automatically receive pending blocks when you do a send, it will only do this if balance isnt high enough to make the transaction.
account_create does not accept an index

Thanks.

**Comment by letskingit** [comment]
Updated to latest, error is gone :+1:

**Comment by letskingit** [comment]
Getting the same error now with requestSend. Let me know if your going to update the remaining methods. 

I'm using using version 2.7.2-V21.2 from maven central.

**Comment by koczadly** [comment]
Support for third-party services are outside the scope of this project at the minute. If the issue is that the requests need to contain different fields, you should be able to create your own request classes by extending the `RpcRequest` class, without needing to make adjustments to the jNano library.

As for the previous error "badly formed hexadecimal UUID string", it sounds like you're passing an incorrect value to the server? I'm not too sure because I haven't used pippin before.

**Comment by koczadly** [comment]
I'd also suggest you update to `2.7.3-V21.2` and configure the `RpcQueryNode` to use an executor which is set to allow errors, like so:
```java
RpcQueryNode node = new RpcQueryNode.Builder()
        .setAddress(new URL("http://localhost:11338"))
        .setRequestExecutor(new HttpRequestExecutor(true))
        .build();
```

This will allow you to see the error messages in exceptions, instead of just receiving a 500 HTTP response code.

**Comment by letskingit** [comment]
uk.oczadly.karl.jnano.rpc.exception.RpcInvalidResponseException: Unable to parse/deserialize the received JSON response.

**Comment by koczadly** [comment]
It sounds like there's some error on the other end that's causing it to send strange response messages. If you wanted to debug further, you could catch the RpcInvalidResponseJsonException and print the response body (there's a method to get it).

**Comment by letskingit** [comment]
response: <html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>

**Comment by koczadly** [comment]
Yeah thats definitely an issue with the RPC provider you're using, it shouldn't be returning non-json data.

If you're running the work generation on the same physical server, you could try using the `WorkSolution.generateMultiThreaded` method built into jNano, although this wont run on GPU's if you're planning on using them. I'd also expect it to be slower than the alternatives, but it might be worth giving it a go.

**Comment by letskingit** [comment]
Yeah thanks for the example code. Much appreciated. Will test it out soon.
